server:
  port: 6060

spring:
  application:
    name: msvc-task

  datasource:
    url: jdbc:mysql://localhost:3306/taskDb
    username: root
    password: Blacky20.

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
