server:
  port: 7070

spring:
  application:
    name: msvc-teacher

  datasource:
    url: jdbc:mysql://localhost:3306/teacherDb
    username: root
    password: Blacky20.

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
