eureka:
  client:
    register-with-eureka: false
server:
  port: 8080

spring:

  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/student/**
        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/course/**
        - id: teachers
          uri: http://localhost:7070
          predicates:
            - Path=/api/teacher/**
        - id: task
          uri: http://localhost:6060
          predicates:
            - Path=/api/task/**